version: '3.8'

services:
  frontend:
    container_name: 'translation-app-frontend'
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./Frontend/:/translation-app-frontend/
    command: yarn dev
    network_mode: "host"


  backend:
    container_name: 'translation-app-backend'
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: bash /translation-app-backend/Backend/setup.sh
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - .:/translation-app-backend
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]

# networks:
#   general-network:
#     driver: bridge