# Generated by Django 4.2.4 on 2023-08-14 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('pdf_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(default='PDFs/sample.pdf', upload_to='PDFs/')),
                ('language', models.CharField(default='en', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('translation_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('file_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_input', to='translation.pdf')),
                ('file_output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='translation.pdf')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0)),
                ('translation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_id_f', to='translation.translation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_f', to='account.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('user_id', 'translation_id'), name='unique_feedback'),
        ),
    ]
